server:
  port: 8080

spring:
  application:
    name: spring-basics

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.epam: ${LOGGING_LEVEL_COM_EPAM:DEBUG}
