server:
  port: 8080

spring:
  application:
    name: spring-basics
  profiles:
    active: QA

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.epam: ${LOGGING_LEVEL_COM_EPAM:DEBUG}
